apiVersion: v1
clusters:
- name: "crispy-octo-cluster"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXlOREUwTVRJME5Wb1hEVE16TURVeU5ERTBNVEkwTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT29zCm5tOFFRaXE2dC9KWmNidG9QK0VwRVZrNFNpV21OenZaYUxRM2NURWlyblM1a3dDWVVpeTZYUjZ1WlV0QW5vLzcKK0hla0pUTVJvek1PcHNrQWZadU9rcXJkNFQ3TlEySWJZMm5TKzVrN1NuS3dMb2tDS3VLTjQvdDNUODlXeDJyQgpWM3VtWXFGU2c5UkUwZVd6TUE4VzZNaXhkUy8wMTEyRlFMblJwS2I0TXBhVzZzaTZMRWR6ZEVkZDNsejJ4bXJnCmh3N3cvNnFGcTlMUEFFVUlQekFJQlFFQUlnMWEvTlpwcXhGRXhrUm5xRnpWcHdDb0kwbjFLQjZ1M0VUayt5STkKZWpEMk1wKzB5RkE2VGRXK2lwanpXNFpLS0VkVXJxeXVScDNqZzZBVmZKOFk3cWsxeUVjOEx0NGREWU0rSFlmQwpmWFhoK3B2SnNvR1l0UDJkajhFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDWWNRcWlYcEtidFRhbGdvUmk1UU9LM0luOURNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCR2Q1cFJZZEdwL3FMNytWWE4xbDZNY3VWWDdzWVlWL1pXeTB6T09RV0NjYnFZVmY4UgpHR0hQZzdDbTdLekNVaWhJMkdad01wL2VaaWVJWHVoU1JaUFk3Mng0eVVUQjduSkdWU1cxMDVmUTJXKzN4VW4xCmlMcVFDOWlNV0lyVTBRbFFyUXdFTVRGMHU4aVRWcnp1eCs0bzBlWjZQYVozbjVRTmJlblBkUTlFVjcySVoxUWgKSDR6Q2sxRnFPM3M4dVp4WnFmR0hzQklIVGZ6ek5UbXRrMkFaL2w3ZWVQYXVtSlVwNmhGU2pPTzlXMW1yYTdKTQovdFFCQXRySFBRNHZaOGZsZnhBSlR0Z0RjNEorYTBMbGdCaml3L2NDQk9ubmZETVNISHFHaklycHF2eXpEUmtECkh5eXhSN0dMYmRLVUYrT3dVYlltYzliUEVDTDY1SDlvNHhMZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://b2c32de1-eb56-4e10-a728-0b89a0f72abf.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@crispy-octo-cluster
  context:
    cluster: "crispy-octo-cluster"
    user: crispy-octo-cluster-admin
current-context: admin@crispy-octo-cluster
kind: Config
preferences: {}
users:
- name: crispy-octo-cluster-admin
  user:
    token: LLIUlpTGXhtYB5r56igV73fjod7rkLyS8AR1oIk9Yfhh0Ntb6jsIXvbS