apiVersion: v1
kind: Secret
metadata:
  name: ruby-app-secrets
type: Opaque
data:
  EMAIL_USERNAME: YXBpa2V5      # Encodez la valeur de votre EMAIL_USERNAME en base64
  EMAIL_PASSWORD: U0cuamdoekR1QlZSV3l1MFZQQUNfUVdzZy55dG9rRWwydGQ5d1o0Vk56Z09YaVdaR0V5MWt5OVJpQ1EwaFhKRmFMQVo0
  DATABASE_URL: bXlzcWwyOi8vdGVzdDpNRVc2bmlKcTNYRUtDLkA1MS4xNTkuMjA1LjU4OjE1MzQ3L2NyaXNweWRi
  APP_SECRET: ZmRqc2tsZmprZGxzZmpkc2ts
  REDIS_URL: cmVkaXM6Ly9jaHJpc3R5OjZaeDNsNjBoZzJZTXBLQmcuQDUxLjE1LjE0Mi4zODo2Mzc5
  EMAIL_FROM: YmllbmVjaHJpc0BoZXRpYy5mcg==